# Generated by Django 3.0.8 on 2020-09-07 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_auto_20200907_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='halls.Hall'),
        ),
    ]
