# Generated by Django 3.0.8 on 2020-09-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_hall_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
