# Generated by Django 3.0.8 on 2020-09-27 01:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('halls', '0006_auto_20200920_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
