# Generated by Django 3.0.8 on 2020-09-27 02:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('halls', '0007_hall_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
